src/XYJPersonalSite/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using XYJPersonalSite.Data;
using XYJPersonalSite.Models.BusinessModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using XYJPersonalSite.Models;
using XYJPersonalSite.Repo;
using XYJPersonalSite.Models.BusinessViewModels;

namespace XYJPersonalSite.Controllers
{
    [Authorize]
    public class BlogsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly ApplicationDbContext _context;

        private readonly BlogsRepo _repo;

        public BlogsController(ApplicationDbContext context,
                    UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager)
        {
            _repo = new BlogsRepo(context);
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [AllowAnonymous]
        // GET: Blogs
        public async Task<IActionResult> Index(string searchString,string typeName,string tagName)
        {
            if (!string.IsNullOrWhiteSpace(searchString))
            {
                ViewBag.Title = "Search result for \"" + searchString + "\"";
                return View(await _repo.Search(searchString));

            }
            if(!string.IsNullOrWhiteSpace(typeName))
            {
                ViewBag.Title = "Articles in " + typeName;
                return View("Index", await _repo.GetListBy(b => b.TypeName == typeName));
            }
            if(!string.IsNullOrWhiteSpace(tagName))
            {
                ViewBag.Title = "Articles in " + tagName;
                return View("Index", await _repo.GetByTag(tagName));
            }
            ViewBag.Title = "All articles";
            return View(await _repo.GetAll());
        }

        //[AllowAnonymous]
        //// GET: Blogs
        //public async Task<IActionResult> GetByType(string typeName)
        //{
        //    ViewBag.Title = "Articles in " + typeName;
        //    return View("Index", await _repo.GetListBy(b => b.TypeName == typeName));
        //}

        //[AllowAnonymous]
        //// GET: Blogs
        //public async Task<IActionResult> GetByTag(string tagName)
        //{
        //    ViewBag.Title = "Articles in " + tagName;
        //    return View("Index", await _repo.GetByTag(tagName));
        //}

        [AllowAnonymous]
        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var blog = await _repo.GetBlogDetail(id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }
        // GET: Blogs/Create
        public IActionResult Create()
        {
            ViewBag.BlogTypes = new SelectList(new BlogTypeRepo(_context).GetAll().Result, "TypeName", "TypeDesc");
            ViewBag.Tags = "";
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Blog,Tags,Blog.Summary,Blog.Title,Blog.Content,Blog.TypeName")] BlogDetailDTO blogDetail)
        {
            blogDetail.Blog.Id = Guid.NewGuid().ToString();
            blogDetail.Blog.CreateTime = DateTime.Now;
            blogDetail.Blog.ModifyTime = DateTime.Now;
            blogDetail.Blog.LikeCount = 0;
            blogDetail.Blog.ReadCount = 0;
            blogDetail.Blog.PostUserId = _userManager.GetUserId(HttpContext.User);
            if (ModelState.IsValid)
            {
                await _repo.Add(blogDetail.Blog);
                if (!string.IsNullOrEmpty(blogDetail.Tags))
                {
                    var tags = blogDetail.Tags.Split(new char[] { ',' });
                    TagsRepo tagsRepo = new TagsRepo(_context);
                    BlogTagRepo blogTagRepo = new BlogTagRepo(_context);
                    foreach (var item in tags)
                    {
                        if (await tagsRepo.GetByKey(item.Trim()) == null)
                        {
                            await tagsRepo.Add(new Tag(item.Trim()));
                        }
                        BlogTag bt = new BlogTag(blogDetail.Blog.Id, item.Trim());
                        await blogTagRepo.Add(bt);
                    }
                }
                return RedirectToAction("Index");
            }
            return View(blogDetail);
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var blogDetail = await _repo.GetBlogDetail(id);
            var blogtypes = await new BlogTypeRepo(_context).GetAll();
            ViewBag.BlogTypes = new SelectList(blogtypes, "TypeName", "TypeDesc", blogDetail.Blog.BlogType);
            if (blogDetail == null)
            {
                return NotFound();
            }
            return View(blogDetail);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Blog,Tags,Blog.Id,Blog.LikeCount,Blog.PostUserId,Blog.CreateTime,Blog.ReadCount,Blog.Summary,Blog.Title,Blog.Content,Blog.TypeName")] BlogDetailDTO blogDetail)
        {
            if (id != blogDetail.Blog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _repo.Edit(blogDetail.Blog);
                    if (!string.IsNullOrEmpty(blogDetail.Tags))
                    {
                        var tags = blogDetail.Tags.Split(new char[] { ',' });
                        TagsRepo tagsRepo = new TagsRepo(_context);
                        BlogTagRepo blogTagRepo = new BlogTagRepo(_context);
                        var query = from bt in _context.BlogTags where bt.BlogId ==id select bt;
                       
                        await blogTagRepo.DeleteBySQL("delete from blogtags where blogid='" + id+"'");
                        foreach (var item in tags)
                        {
                            if (await tagsRepo.GetByKey(item.Trim()) == null)
                            {
                                await tagsRepo.Add(new Tag(item.Trim()));
                            }
                            BlogTag bt = new BlogTag(blogDetail.Blog.Id, item.Trim());
                            await blogTagRepo.Add(bt);
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blogDetail.Blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["PostUserId"] = new SelectList(_context.Users, "Id", "Id", blogDetail.Blog.PostUserId);
            return View(blogDetail);
        }

        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var blog = await _context.Blogs.SingleOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var blog = await _context.Blogs.SingleOrDefaultAsync(m => m.Id == id);
            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool BlogExists(string id)
        {
            return _context.Blogs.Any(e => e.Id == id);
        }

    }
}

src/XYJPersonalSite/ViewComponents/BlogTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using XYJPersonalSite.Data;
using XYJPersonalSite.Repo;

namespace XYJPersonalSite.ViewComponents
{
    public class BlogTypesViewComponent:ViewComponent
    {
        private readonly BlogTypeRepo _repo;
        public BlogTypesViewComponent(ApplicationDbContext context)
        {
            _repo = new BlogTypeRepo(context);
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("Types", await _repo.GetAll());
        }
    }
}

src/XYJPersonalSite/ViewComponents/TagsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using XYJPersonalSite.Data;

namespace XYJPersonalSite.ViewComponents
{
    public class TagsViewComponent:ViewComponent
    {
        private readonly TagsRepo _repo;
        public TagsViewComponent(ApplicationDbContext context)
        {
            _repo = new TagsRepo(context);
        }

        public async Task<IViewComponentResult> InvokeAsync(int topCount)
        {
            return View("TopTag",await _repo.GetTop(topCount));
        }
    }
}

src/XYJPersonalSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - xuyongjie</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="http://bootswatch.com/yeti/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top absolute-position">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Blogs" asp-action="Index" class="navbar-brand">xuyongjie</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">All Articles<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            @await Component.InvokeAsync("BlogTypes")
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About Me</a></li>
                </ul>
                <form class="navbar-form navbar-left" role="search" asp-action="Index" method="get">
                    <div class="form-group">
                        <input name="searchString" class="form-control" placeholder="Search" />
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
            <div class="col-md-3 hidden-sm hidden-xs">
                @await Component.InvokeAsync("Tags",new { topCount=20 })
            </div>
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - xuyongjie</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>